apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-persistent-storage
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
